---
separator:
position: 1
debug: true
nodes:
  - name: macroriever 
    parent: moonlight
    ignore_if_has:
      - muds
    remove:
      - "@" 
      - \
    explicit_search:
      - "main street" 
      - "lucky12"
    explicit_search_combine:
      - ["master", "node"]
    fuzzy_search: macroriever 
    threshold: 0.85